### ISSUE TITLE
could not compile dependency :connection

### ISSUE THREAD

**Issue by guillaumebailleul** [adamzapasnik/vscode-elixir-test-explorer#9]
Hello, the plugin seems to not work on my umbrella project. The command `mix test --trace --seed=0 --only=""` works on my terminal but I got an error on visual studio.

It works find with a regular new phoenix project.

Do you have an idea of what's wrong ?

Best regards

```
Command failed: mix test --trace --seed=0 --only=""
could not compile dependency :connection, "mix compile" failed. You can recompile this dependency with "mix deps.compile connection", update it with "mix deps.update connection" or clean it with "mix deps.clean connection"
** (CaseClauseError) no case clause matching: {:repaired, #Reference<0.1377449741.605028358.52651>, {:recovered, 636}, {:badbytes, 0}}
    (stdlib 3.15.1) ets.erl:808: :ets.tab2file/3
    (mix 1.12.1) lib/mix/compilers/application_tracer.ex:193: Mix.Compilers.ApplicationTracer.write_manifest/2
    (mix 1.12.1) lib/mix/compilers/application_tracer.ex:14: Mix.Compilers.ApplicationTracer.init/1
    (mix 1.12.1) lib/mix/compilers/elixir.ex:81: Mix.Compilers.Elixir.compile/6
    (mix 1.12.1) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.12.1) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.12.1) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.12.1) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
```

**Comment by adamzapasnik** [comment]
could you remove _build and deps folders and try to fetch deps and recompile them again 🤔
